# Generated by Django 5.2.11 on 2026-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiltbites_app', '0002_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
